const config = {
  DOMAIN: 'tictactoe.cz',
  EMAIL: 'cibulka.me@gmail.com',
  MAX_LENGTH_NICKNAME: 15,
  MIN_LENGTH_NICKNAME: 3,
  SNAKE_BOARD_ROWS: 15,
  SNAKE_BOARD_CELLS: 21,
  SNAKE_INITIAL_SIZE: 5,
  SNAKE_SPEED: 400,
  TETRIS_BOARD_ROWS: 20,
  TETRIS_BOARD_CELLS: 10,
  TETRIS_SPEED_LEVEL_INCREASE: 27,
  TETRIS_ROWS_IN_LEVEL: 15,
  TETRIS_SPEED_DROP: 20,
  TETRIS_SPEED_INITIAL: 500,
  TIC_TAC_TOE_MOVE_LIMIT: 1000 * 60,
  TIC_TAC_TOE_SIZE: 15,
  TIC_TAC_TOE_SHOWN: 5,
};

export default config;
